# -*- coding: utf-8 -*-
"""Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDi4TKpf-oqNT34q4_AI8nURDavuDdYB
"""

import numpy as np
import pandas as pd

dataset=pd.read_csv("/content/Churn_Modelling.csv")

dataset.head()

dataset.info()

print(dataset.isnull().sum())
print(dataset.describe())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))

ax = sns.countplot(x='Exited', data=dataset)

for container in ax.containers:
    ax.bar_label(container)

plt.title("Customer Churn Distribution")
plt.xlabel("Exited (0 = No Churn, 1 = Churn)")
plt.ylabel("Number of Customers")

plt.show()

from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
categorical_cols = ['Surname','Gender','Geography']
for col in categorical_cols:
    dataset[col] = labelencoder.fit_transform(dataset[col])

dataset.info()

from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
categorical_cols = ['Surname','Gender','Geography']
for col in categorical_cols:
    dataset[col] = labelencoder.fit_transform(dataset[col])

X = dataset.drop(['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis=1)
y = dataset['Exited']

dataset = pd.get_dummies(dataset, columns=['Geography', 'Gender'], drop_first=True)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(dataset['Exited'].value_counts())
RandomForestClassifier(class_weight='balanced')

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Train model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

