# -*- coding: utf-8 -*-
"""Real_Estate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154cHVo9i5aZ_oJo0oloc9y2XM8oarzPA
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import folium

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings("ignore")

df1 = pd.read_csv("/content/train_part1.csv")
df2 = pd.read_csv("/content/train_part2.csv")

print("Dataset 1 Shape :", df1.shape)
print("Dataset 2 Shape :", df2.shape)

print("\nDataset 1 Columns")
print(df1.columns)

print("\nDataset 2 Columns")
print(df2.columns)

print("\nDataset 1")
print(df1.head())

print("\nDataset 2")
print(df2.head())

data = pd.concat([df1, df2], ignore_index=True)

print("\nMerged Dataset Shape :", data.shape)

print("\nMissing Values")
print(data.isnull().sum())

data.drop_duplicates(inplace=True)

print("\nShape After Removing Duplicates")
print(data.shape)

df1.info()
df2.info()

required_columns = ["Latitude","Longitude","Price_INR","Locality",
"SuperBuiltUpArea_sqft"]

data = data[required_columns]

data = data.dropna()

print("\nFinal Dataset Shape")
print(data.shape)

data["Latitude"] = pd.to_numeric(data["Latitude"])
data["Longitude"] = pd.to_numeric(data["Longitude"])
data["Price_INR"] = pd.to_numeric(data["Price_INR"])
data["SuperBuiltUpArea_sqft"] = pd.to_numeric(
    data["SuperBuiltUpArea_sqft"]
)

print("\nDataset Information")
print(data.info())

print("\nStatistical Summary")
print(data.describe())

print("\nMissing Values After Cleaning")
print(data.isnull().sum())

data.to_csv("Cleaned_Dataset.csv", index=False)

print("\nCleaned Dataset Saved Successfully.")

features = data[["Latitude","Longitude","Price_INR","SuperBuiltUpArea_sqft"]]

print("\nSelected Features")
print(features.head())

scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

scaled_df = pd.DataFrame(
    scaled_features,
    columns=features.columns
)

print("\nScaled Data")
print(scaled_df.head())

wcss = []

for i in range(1, 11):

    model = KMeans(
        n_clusters=i,
        init='k-means++',
        random_state=42,
    )

    model.fit(scaled_df)

    wcss.append(model.inertia_)

plt.figure(figsize=(8,5))

plt.plot(
    range(1,11),
    wcss,
    marker='o',
    linewidth=2
)

plt.title("Elbow Method")

plt.xlabel("Number of Clusters")

plt.ylabel("WCSS")

plt.grid(True)

plt.savefig("Elbow_Method.png")

plt.show()

k = 4

print("\nOptimal Number of Clusters =", k)

kmeans = KMeans(
    n_clusters=k,
    init='k-means++',
    random_state=42,
)

clusters = kmeans.fit_predict(scaled_df)

data["Cluster"] = clusters

print("\nCluster Count")

print(data["Cluster"].value_counts())

print("\nCluster Centers")

centers = scaler.inverse_transform(kmeans.cluster_centers_)

centers = pd.DataFrame(
    centers,
    columns=["Latitude","Longitude","Price_INR","SuperBuiltUpArea_sqft"]
)

print(centers)

data.to_csv(
    "Clustered_House_Data.csv",
    index=False
)

print("\nClustered Dataset Saved Successfully.")

import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))

colors = ["red","blue","green","orange"]

for i in range(k):

    cluster = data[data["Cluster"] == i]

    plt.scatter(
        cluster["SuperBuiltUpArea_sqft"],
        cluster["Price_INR"],
        color=colors[i],
        label="Cluster "+str(i),
        alpha=0.7
    )

plt.title("Area vs Price")

plt.xlabel("Area (sqft)")

plt.ylabel("Price (INR)")

plt.legend()

plt.grid(True)

plt.savefig("Area_vs_Price.png")

plt.show()

Classic = data["Price_INR"].quantile(0.33)
Affordable = data["Price_INR"].quantile(0.66)

def property_level(price):

    if price <= Classic:
        return "Classic"

    elif price <= Affordable:
        return "Affordable"

    else:
        return "Luxury"

data["Property_Level"] = data["Price_INR"].apply(property_level)

print(data[
    [
        "Price_INR",
        "Property_Level"
    ]
].head())

import folium
from folium.plugins import MarkerCluster

center_lat = data["Latitude"].mean()
center_lon = data["Longitude"].mean()

real_map = folium.Map(
    location=[center_lat, center_lon],
    zoom_start=11,
    tiles="OpenStreetMap"
)

marker_cluster = MarkerCluster().add_to(real_map)

for index, row in data.iterrows():

    if row["Property_Level"] == "Luxury":
        color = "red"

    elif row["Property_Level"] == "Affordable":
        color = "blue"

    else:
        color = "green"

    popup = f"""
    <b>Location :</b> {row['Locality']}<br>

    <b>Price :</b> ₹ {row['Price_INR']:,}<br>

    <b>Area :</b> {row['SuperBuiltUpArea_sqft']} Sq.ft<br>

    <b>Property :</b> {row['Property_Level']}<br>
    """

    icon = folium.Icon(
        color=color,
        icon="home",
        prefix="fa"
    )

    folium.Marker(
        location=[
            row["Latitude"],
            row["Longitude"]
        ],
        popup=folium.Popup(popup, max_width=300),
        icon=icon
    ).add_to(marker_cluster)

display(real_map)