# -*- coding: utf-8 -*-
"""E-commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRjmvs1sM8m0fhBWvpWfaGNMcle4C23y
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

data = pd.read_csv(
    "/content/amazon_ecommerce_1M.csv",
    low_memory=False
)

print(data.shape)
print(data.dtypes)

data.head()

data.info()

data.isnull().sum()

data.fillna(data.mean(numeric_only=True), inplace=True)

data[col] = data[col].fillna(data[col].mode()[0])
data = data.infer_objects(copy=False)

data.describe()

data["purchase_date"] = pd.to_datetime(data["purchase_date"])
data["month"] = data["purchase_date"].dt.month
data["sales"] = data["final_price"]

import matplotlib.pyplot as plt

monthly_sales = data.groupby("month")["sales"].sum()

plt.figure(figsize=(10,5))
plt.plot(monthly_sales.index, monthly_sales.values, marker='o')
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.title("Monthly Sales Trend")
plt.grid(True)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = data[["price","discount","rating","review_count","stock","seller_rating"]]

y = data["final_price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred)
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    color="red"
)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted Price")
plt.grid(True)
plt.show()

print(data.columns.tolist())

brand_sales = data.groupby("brand")["sales"].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
brand_sales.plot(kind="bar")
plt.xlabel("Brand")
plt.ylabel("Sales")
plt.title("Top 10 Brands by Sales")
plt.show()

data["year"] = data["purchase_date"].dt.year
data["day"] = data["purchase_date"].dt.day
data["dayofweek"] = data["purchase_date"].dt.dayofweek

le = LabelEncoder()

categorical_cols = ["category","subcategory","brand","location","device","payment_method","delivery_status","user_id","product_id",
         "seller_id","purchase_date","year","month","day","dayofweek","is_returned"]

for col in categorical_cols:
    data[col] = le.fit_transform(data[col])

data["is_returned"] = data["is_returned"].astype(int)

data.info()

X = data[
    ["category","subcategory","brand","price","discount","rating","review_count","stock","seller_rating",
        "shipping_time_days","location","device","payment_method","is_returned","delivery_status","year","month",
        "day","dayofweek"
    ]
]

y = data["final_price"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R2 Score :", r2_score(y_test, y_pred))
print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE :", mean_squared_error(y_test, y_pred) ** 0.5)

result = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})

print(result.head(10))

accuracy = r2_score(y_test, y_pred) * 100
print(f"Model Accuracy: {accuracy:.2f}%")